### ISSUE TITLE
unlock screen not possible in Manjaro

### ISSUE THREAD

**Issue by stoyanov-ge** [bluesabre/xfce4-screensaver#8]
#### Expected behaviour
when I lock screen and want to return to my desktop, I want to see a user/password fields which allows me to enter my password and unlock the screen.

#### Actual behaviour

Screen is flickering on mouse move and going black when I stop moving it. I am using second monitor on my laptop. Primary one is disabled.

#### Steps to reproduce the behaviour
I just installed xfce4-screensaver from the master branch on up-to-date Manjaro XFCE linux.

#### XFCE general version
4.13

#### Package version
$ xfce4-screensaver --version
xfce4-screensaver 1.20.0

#### Linux Distribution
Manjaro 18.02 (+latest updates)

**Comment by stoyanov-ge** [comment]
I managed to force install of version 0.1.3 and now unlock is working normally.

**Comment by bluesabre** [comment]
Thanks for the update. Closing this issue.
