### ISSUE TITLE
Spanned Wallpapers Cause Login Box Split Between Windows

### ISSUE THREAD

**Issue by bambam2k3** [bluesabre/xfce4-screensaver#9]
#### Expected behaviour
When triggering the unlock, the login box is displayed on either a specified or default monitor

#### Actual behaviour
When triggering the unlock, the login box is split between two screens

#### Steps to reproduce the behaviour
I can reproduce this with 2 1980x1020 Monitors
Use the attached wallpaper and set it to Spanning Screens as the style in Desktop settings
![firewatch](https://user-images.githubusercontent.com/17817325/56105241-45afbc00-5f09-11e9-8e08-dcf5eedf206f.jpg)

Lock the screen with either keyboard or let the screensaver lock it.

Move the mouse so it calls the Unlock
Notice the unlock dialog is split between the two screens versus being fully on one screen or another.

#### XFCE general version
4.12

#### Package version
1.4

#### Linux Distribution
Xubuntu 19.04

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/xfce4-screensaver/+bug/1824751

**Comment by bluesabre** [comment]
Closing in favor of https://bugzilla.xfce.org/show_bug.cgi?id=15591 on the Xfce Bugzilla. Thanks!
